import type { Metadata } from "next";
import { opensans } from "./ui/fonts";
import "./globals.css";
import Navigation from "./ui/navigation";
import Footer from "./ui/footer";

export const metadata: Metadata = {
  title: "El Mercadito Grab & Go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${opensans.className} antialiased`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
